columns:
- header: 'E-mail'
  key: 'E-mail'
  width: 10
- header: 'ID'
  key: 'ID'
  width: 10
- header: '비밀번호'
  key: '비밀번호'
  width: 10
- header: '이름'
  key: '이름'
  width: 10
- header: '회원그룹'
  key: '회원그룹'
  width: 10
- header: '회원등급'
  key: '회원등급'
  width: 10
- header: '성별'
  key: '성별'
  width: 10
- header: '연락처'
  key: '연락처'
  width: 10
- header: '홈페이지'
  key: '홈페이지'
  width: 10
- header: '우편번호'
  key: '우편번호'
  width: 10
- header: '주소'
  key: '주소'
  width: 10
- header: '상세주소'
  key: '상세주소'
  width: 10
- header: '생년월일'
  key: '생년월일'
  width: 10
- header: '포인트'
  key: '포인트'
  width: 10

# 연락처: 핸드폰 번호?
# 상세 주소
extra_vars:
- handphone
- home_address















